# Generated by Django 4.1.7 on 2025-05-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='getModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='Даны вещественные числа: A, B, C. Определить, выполняются ли неравенства A < B < C или A < B > C и какое именно неравенство выполняется.', max_length=255, verbose_name='Формулировка')),
                ('a', models.IntegerField(default=0, verbose_name='Значение A')),
                ('b', models.IntegerField(default=0, verbose_name='Значение B')),
                ('c', models.IntegerField(default=0, verbose_name='Значение C')),
                ('result', models.CharField(default='Ответ', max_length=255, verbose_name='Ответ')),
                ('current_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения(save)')),
            ],
            options={
                'verbose_name': ' Таблица результатов',
                'verbose_name_plural': 'Таблицы результатов',
                'ordering': ('-pk',),
            },
        ),
    ]
